export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL ="USER_LOGIN_FAIL";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL ="USER_SIGNUP_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const USER_GET_ALL_REQUEST = "USER_GET_ALL_REQUEST";
export const USER_GET_ALL_SUCCESS = "USER_GET_ALL_SUCCESS";
export const USER_GET_ALL_FAIL = "USER_GET_ALL_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const MEASUREMENT_CREATE_REQUEST = "MEASUREMENT_CREATE_REQUEST";
export const MEASUREMENT_CREATE_SUCCESS = "MEASUREMENT_CREATE_SUCCESS";
export const MEASUREMENT_CREATE_FAIL = "MEASUREMENT_CREATE_FAIL";

export const MEASUREMENT_GET_REQUEST = "MEASUREMENT_GET_REQUEST";
export const MEASUREMENT_GET_SUCCESS = "MEASUREMENT_GET_SUCCESS";
export const MEASUREMENT_GET_FAIL = "MEASUREMENT_GET_FAIL";


